### ISSUE TITLE
Термукс

### ISSUE THREAD

**Issue by detrixVR** [mishakorzik/Termux#1]
Команды

**Comment by detrixVR** [comment]
> Команды

**Comment by mishakorzik** [comment]
?

**Comment by detrixVR** [comment]
Just liked yours app

**Comment by wmwkapitw** [comment]
кто нибудь знает как через термукс кали установить

**Comment by bust6k** [comment]
Кто нибудь знает как сообщить termux  из какого пакета ты хочешь использлвать команду is
